spring:
  application:
    name: perftest
  datasource:
    url: jdbc:oracle:thin:@//mock-oracle.brazilsouth.azurecontainer.io:1521/xe
    username: MOCK
    password: MOCK
    driver-class-name: oracle.jdbc.OracleDriver
  output:
    ansi:
      enabled: ALWAYS
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.Oracle12cDialect
        default_schema: MOCK
        proc:
          param_null_passing: true
        jdbc:
          lob:
            non_contextual_creation: true
  jmx:
    enabled: false